version: "3.8"

services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_FORWARDER_PORT:-8080}:8080"
    volumes:
      - .:/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: "${MYSQL_PASS}"
      MARIADB_DATABASE: "${MYSQL_DB}"
      MARIADB_USER: "${MYSQL_USER}"
      MARIADB_PASSWORD: "${MYSQL_PASS}"
    ports:
      - "${DB_FORWARDER_PORT:-3306}:3306"
    volumes:
      - ./starter.sql:/docker-entrypoint-initdb.d/starter.sql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
