-- +++ UP Migration
CREATE TABLE test (
	colum1 INT NOT NULL,
	colum2 VARCHAR(100) NOT NULL,
	colum3 BOOLEAN DEFAULT FALSE,
	colum4 DATE DEFAULT NULL,
	colum5 DECIMAL(10, 2) DEFAULT 0.00,
	colum6 TEXT,
	colum7 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	colum8 BIGINT DEFAULT 0,
	colum9 CHAR(1) DEFAULT 'A',
	colum10 JSON DEFAULT NULL
);
-- --- DOWN Migration
DROP TABLE IF EXISTS test;